### ISSUE TITLE
display milestone information in Homer

### ISSUE THREAD

**Issue by jtauber** [scaife-viewer/scaife-skeleton#28]
- [ ] extract information from TEI XML
- [ ] work out how to represent it and convey it via API
- [ ] work out how to display it in reading environment
